spring:
  datasource:
    url: jdbc:postgresql://localhost5432/springbootjpa?createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-update
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"